'use client';

import { Button } from './ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from './ui/card';
import { Skeleton } from './ui/skeleton';
import { Download, Sparkles } from 'lucide-react';
import * as React from 'react';
import { downloadSummaryAsXLSX } from '@/lib/xlsx-utils';

interface SummaryDisplayProps {
  summary: string | null;
  isLoading: boolean;
}

export function SummaryDisplay({ summary, isLoading }: SummaryDisplayProps) {
  
  const handleDownload = () => {
    if (summary) {
        downloadSummaryAsXLSX(summary);
    }
  }

  return (
    <Card className="h-full">
      <CardHeader>
        <CardTitle className="text-xl flex items-center gap-2">
          <Sparkles className="text-accent"/>
          AI Generated Summary
        </CardTitle>
        <CardDescription>
          This summary is generated by AI based on your selected data and filters.
        </CardDescription>
      </CardHeader>
      <CardContent>
        {isLoading ? (
          <div className="space-y-3">
            <Skeleton className="h-5 w-4/5" />
            <Skeleton className="h-5 w-full" />
            <Skeleton className="h-5 w-full" />
            <Skeleton className="h-5 w-3/4" />
          </div>
        ) : summary ? (
          <div>
            <p className="text-sm whitespace-pre-wrap">{summary}</p>
            <Button className="mt-6" onClick={handleDownload}>
              <Download className="mr-2 h-4 w-4" />
              Download Summary
            </Button>
          </div>
        ) : (
          <div className="text-center text-muted-foreground py-16">
            <p>Your summary will appear here once generated.</p>
          </div>
        )}
      </CardContent>
    </Card>
  );
}
